#!/bin/bash
# Generate version information at build time

set -e

# Get version from git tag, or default to dev if no tag
VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "dev")

# Get build date
BUILD_DATE=$(date -u +"%Y-%m-%d")

# Create the version file
cat > "$1" << EOF
// Auto-generated version information
// Do not edit this file manually

struct Version {
    static let version = "$VERSION"
    static let buildDate = "$BUILD_DATE"
}
EOF

echo "Generated version: $VERSION"

