name: Build and Test

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for git describe
      
    - name: Setup Swift
      run: |
        # Use the system Swift that comes with Xcode
        echo "Using system Swift version:"
        swift --version
        
    - name: Show version info
      run: make version
      
    - name: Build
      run: make build
      
    - name: Test
      run: make test
      
    - name: Prepare binary artifact
      run: |
        cp .build/release/pastedown ./pastedown
        chmod +x ./pastedown
        
    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: pastedown-binary
        path: pastedown
        retention-days: 30

